### PR TITLE
Update code.yml

### PR DESCRIPTION
**Pull request by mlamtahri**
Adding Epi Info to the list of open source projects.

### CODE REVIEW

**Comment by leebrian** [comment]
Thanks @mlamtahri Really neat you added in Epi-Info. I think that's CDC's oldest repo. Keep eye on the [releases](https://github.com/CDCgov/opencdc/releases) section for when the change is published to the site. We're bundling up suggestions and the next routine update will be around Feb 1.

**Comment by mlamtahri** [comment]
Hi Brian,
The Epi info repository link is broken. Epi info products have their own repository in GitHub. They don’t exist under https://github.com/CDCgov<https://github.com/CDCgov/SDP-Vocabulary-Service>. Any suggestion on how to fix this issue?
[cid:image002.png@01D4B74D.37692730]
Also, is it possible to include the Epi info logo ?
Thank you
Mohammed Lamtahri

**Comment by leebrian** [comment]
Sorry, the url issue is a bug that we’ll fix in the templates for rendering the code page. You can watch the progress under https://github.com/CDCgov/opencdc/issues/31 for when it gets fixed. 

It’s certainly possible to use your own image, please use the yaml attribute “image” under your entry in the code.yml entry and add a pull request with your desired image in the assets/img directory. For an example of a code set that does this look at the Foundation Services entry.

Also, if you are looking at your entry, would you reformat the tags you chose? Since tags are displayed as hashtags it looks a bit confusing to show “#.net MVC.” I’m not sure your preference for how this best displays for whether it’s two separate tags or there’s no space. Or a dash. Or other.

**Comment by mlamtahri** [comment]
Ok, Thank you!  I will make the appropriate changes to include the Epi info logo.

**Pull request merged**
