### PR TITLE
Add maps repo to site

### PR DESCRIPTION
**Pull request by danielimmke**

### CODE REVIEW

**Comment by leebrian** [comment]
Great contrib, I think this will help folks use the maps module. Your current tagline is about blockchain, would you update the PR with the tagline you'd like to display?

**Comment by danielimmke** [comment]
Updated!

**Comment by leebrian** [comment]
Great, thanks. I'm never quite sure about blockchain projects and wanted to check with you incase data viz components had jumped on the blocktrain.

**Comment by leebrian** [comment]
Please keep an eye out on the releases tab for when the web site is updated. We typically update around the first of each month.

**Pull request merged**
