### PR TITLE
SDPV-1175] - code page content update to sdp-v

### PR DESCRIPTION
**Pull request by cssandlin**
updated description content on code page for SDP-Vocabulary-Service and SDP-CBR.

### CODE REVIEW

**Comment by leebrian** [comment]
I think your fork is out of sync. It will help me merge future PRs if you rsync your fork before changes. I went ahead and manually reconciled the merge because I had never seen GitHub’s “resolve in web ide” and wanted to test it out, on my phone, at dinner. I think it worked.

Thanks for the submission and keep an eye out for the next version tag to let you know when your updates make it to the site.

**Comment by cssandlin** [comment]
Yes, it is out of sync.  I thought you'd see changes but wasn't sure if you'd be notified about a sync.  I'll re-sync.  I've been testing features on my phone as well.  Simple merges, reviews, etc.

Thanks, will do!

**Comment by cssandlin** [comment]
I re-synced my fork.  I'm not seeing the updates.  Should I re-commit?

**Comment by leebrian** [comment]
No, you’re good. It would only apply on future PRs. I went ahead and merged this PR manually despite it being from an old branch.

**Comment by leebrian** [comment]
OK, I see what I did. I manually merged cdcgov/master into csslandlin/sdpv-content-update, not at all what I intended to do. I also undid the edits you intended to make. Curious that i have write permissions to your branch.

Sorry about my confusion and extra work for you. Since you resynced your fork, would you mind creating a new branch with your changes in them and submit a new PR? I think that will be easier than me making the change into your manually merged branch and then submitting a new PR.

**Pull request merged**
