### PR TITLE
Update code.yml

### PR DESCRIPTION
**Pull request by mlamtahri**
Added Epi Info logo.

### CODE REVIEW

**Comment by leebrian** [comment]
Cool. Thanks. What about "Epi Info?" Should that be "EpiInfo" or "Epi-Info". Currently it shows up as #Epi info. Which is fine if you're ok with it, but may be disorienting to users. It looks like there's posts using both "#EpiInfo" and "#Epi-Info" https://twitter.com/search?q=%23EpiInfo&src=typd

**Comment by mlamtahri** [comment]
Brian,
I'm not able to add  the Epi info logo to the directory assets/img. Below is the message that I get when I try to upload the image to GitHub.
[cid:image001.jpg@01D4B7D4.2954F390]
Attached is the image I'm trying to upload.

Also, I will change the tag "Epi Info" to "EpiInfo".
Thank you
Mohammed lamtahri

**Comment by leebrian** [comment]
I didn't see the message or image you reference. Are you adding the image to the patch-2 branch? You should be able to upload the new image. Would you please describe the steps you take to upload? 

If you're using the web interface, you'll need to be directly in your branch folder on https://github.com/mlamtahri/opencdc/tree/patch-2/assets/img using your browser. 

If you're getting this error, it's usually because the browser is navigated to the master branch (where few people have push permissions)
image

**Comment by mlamtahri** [comment]
Sorry I was using the wrong branch…I’m able to upload image.
Thank you
ML

**Pull request merged**
