### PR TITLE
Add links to SDP API guidance

### PR DESCRIPTION
**Pull request by hadleynet**
The wiki links are kind of ugly but it looks like the site style is to show the full link rather than hide the URL under a text description so I went with that.

I added the API guidance to both the Code and API pages since I couldn't decide which was most appropriate.

### CODE REVIEW

**Comment by leebrian** [comment]
This is so neat Marc, thanks. For entries, I think having them as data rather than presentation will help us syndicate the data to other sources who may also need to render the links in various formats. Would you mind adding these items to the api.yml data file? They will show up in the apis section, but still be searchable from the entire site.

If you like, you can add a cool little sdp logo to the section or something to highlight they have a thematic group.

**Comment by hadleynet** [comment]
OK, I can do that. Would you be open to change to the apis.html file and api.yml structure to make the endpoint link optional and allow multiple links for documentation? That way I could group links to all the wiki pages in a single entry.

**Comment by leebrian** [comment]
Yes, certainly. It's optional now so you can leave endpoint blank or N/A.

For documentation, I think having the documentation links repeat will help. Would you please refactor a loop for more than one documentation link?

**Comment by hadleynet** [comment]
The current pull request renders a documentation table row with a single link and a new "Additional Links" row that supports an array of links with description text.

Would you prefer that all the links are in the same documentation table row? Would you also prefer that I drop the new "links" field in the yml and make the docs yml field an array? Note that this would require all of the existing entries to be edited.

If we make docs an array then I think it would be good to also add some descriptive text for each link in case the URL isn't self-descriptive enough. I did this for the new links fields - what do you think to that approach?

I also wondered about top aligning the text in each row of the entry table - having the label in the middle of a block of links doesn't look quite right to me - but maybe that's just me?

**Comment by leebrian** [comment]
Thanks, I think this is cleaner as it doesn't require programs to update url for existing items. Please keep an eye on releases for when the site is updated with this new content. This typically happens toward the end of each month.

**Pull request merged**
